version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /Users/datascientist/Documents/Personal/microblog/web/project/static:/www/static
    depends_on:
      - web
